# 13f2_rds_diff.R — compare bundled rds against freshly parsed files (audit only)
suppressPackageStartupMessages({ library(readr); library(dplyr) })
m <- read_csv("D:/NHANES/data/nhanes_mort2019.csv", show_col_types = FALSE)
r <- readRDS("D:/NHANES/data/mortality/LMF2019_public_CJ.rds")
rs <- as.integer(r$seqn)
only_rds <- setdiff(rs, m$seqn)
only_parsed <- setdiff(m$seqn, rs)
cat("in rds not parsed:", length(only_rds), "\n")
cat("in parsed not rds:", length(only_parsed), "\n")
cat("first-digit of rds-only seqn:\n"); print(table(substr(sprintf("%05d", only_rds), 1, 1)))
cat("first-digit of parsed-only seqn:\n"); print(table(substr(sprintf("%05d", only_parsed), 1, 1)))
cat("rds-only mortstat==1:", sum(r$mortstat[rs %in% only_rds] == 1, na.rm = TRUE), "\n")
cat("parsed-only mortstat==1:", sum(m$mortstat[m$seqn %in% only_parsed] == 1, na.rm = TRUE), "\n")
